# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1614b1dbc9d36e8b1ce3e067ee439c095dc8007c16303faf5679c7164f83fd16e0c36800c4d79d7caf9029250090f7ebb54129eaa97fe87e3e00c8a976c11b4

test:
  secret_key_base: 09a93decfc62cff251cb64d0e64f8b902198e9d1682558d1e4df7d0215c6eac9c7d4d745eb46d1450bc26398adbf8542538324640f9ff17e420992ceaaab0982

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
